- SOURCES/0001-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0002-Add-TrueNAS-multipath-config.patch
- SOURCES/0003-feat-drivers-add-CephFS-GlusterFS-and-XFS-drivers.patch
- SOURCES/0004-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0005-Re-add-the-ext4-driver-for-users-who-need-to-transit.patch
- SOURCES/0006-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0007-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0008-If-no-NFS-ACLs-provided-assume-everyone.patch
- SOURCES/0009-Fix-regression-added-by-XSI-915.patch
- SPECS/sm.spec
Koji build: http://koji.xcp-ng.org/taskinfo?taskID=18929
> Sync patches with 2.30.3-8.2 branch

- SOURCES/0008-Support-IPv6-in-NFS.patch
- SPECS/sm.spec
Signed-off-by: BenjiReis <benjamin.reis@vates.fr>
> Support IPv6 in NFS

- SOURCES/0001-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0002-Add-TrueNAS-multipath-config.patch
- SOURCES/0003-feat-drivers-add-CephFS-GlusterFS-and-XFS-drivers.patch
- SOURCES/0004-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0005-Re-add-the-ext4-driver-for-users-who-need-to-transit.patch
- SOURCES/0006-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0007-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0008-If-no-NFS-ACLs-provided-assume-everyone.patch
- SOURCES/0009-Fix-regression-added-by-XSI-915.patch
- SOURCES/0010-Added-SM-Driver-for-MooseFS.patch
- SPECS/sm.spec
Koji build: http://koji.xcp-ng.org/taskinfo?taskID=19142
> Add experimental MooseFS driver

- SOURCES/0001-backport-of-ccd121cc248d79b749a63d4ad099e6d5f4b8b588.patch
- SOURCES/0002-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0003-Add-TrueNAS-multipath-config.patch
- SOURCES/0004-feat-drivers-add-CephFS-GlusterFS-and-XFS-drivers.patch
- SOURCES/0005-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0006-Re-add-the-ext4-driver-for-users-who-need-to-transit.patch
- SOURCES/0007-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0008-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0009-If-no-NFS-ACLs-provided-assume-everyone.patch
- SOURCES/0010-Added-SM-Driver-for-MooseFS.patch
- SOURCES/0011-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch
- SPECS/sm.spec
Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
> Add 0011-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch

- SOURCES/0001-backport-of-ccd121cc248d79b749a63d4ad099e6d5f4b8b588.patch
- SOURCES/0002-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0003-Add-TrueNAS-multipath-config.patch
- SOURCES/0004-feat-drivers-add-CephFS-GlusterFS-and-XFS-drivers.patch
- SOURCES/0005-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0006-Re-add-the-ext4-driver-for-users-who-need-to-transit.patch
- SOURCES/0007-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0008-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0009-If-no-NFS-ACLs-provided-assume-everyone.patch
- SOURCES/0010-Added-SM-Driver-for-MooseFS.patch
- SOURCES/0011-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch
- SOURCES/0012-MooseFS-SR-uses-now-UUID-subdirs-for-each-SR.patch
- SOURCES/0013-Fix-is_open-call-for-many-drivers-25.patch
- SOURCES/0014-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
- SPECS/sm.spec
- Add 0013-Fix-is_open-call-for-many-drivers-25.patch
- Add 0014-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
> Sync patches with our latest 2.30.7-8.2 branch

- SOURCES/0013-Fix-is_open-call-for-many-drivers-25.patch
- SOURCES/0014-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
- SPECS/sm.spec
Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
> Fix regression caused by is_open patch (LVHDSR + XCP-ng drivers)

- SOURCES/0001-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0002-Add-TrueNAS-multipath-config.patch
- SOURCES/0003-feat-drivers-add-CephFS-GlusterFS-and-XFS-drivers.patch
- SOURCES/0004-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0005-Re-add-the-ext4-driver-for-users-who-need-to-transit.patch
- SOURCES/0006-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0007-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0008-Added-SM-Driver-for-MooseFS.patch
- SOURCES/0009-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch
- SOURCES/0010-MooseFS-SR-uses-now-UUID-subdirs-for-each-SR.patch
- SOURCES/0011-Fix-is_open-call-for-many-drivers-25.patch
- SOURCES/0012-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
- SOURCES/0013-Fix-code-coverage-regarding-MooseFSSR-and-ZFSSR.patch
- SPECS/sm.spec
Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
> Re-enable tests, test file coverage rate is now 100%

- SOURCES/0001-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0002-Add-TrueNAS-multipath-config.patch
- SOURCES/0003-feat-drivers-add-CephFS-and-GlusterFS-drivers.patch
- SOURCES/0004-feat-drivers-add-XFS-driver.patch
- SOURCES/0005-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0006-Re-add-the-ext4-driver-for-users-who-need-to-transit.patch
- SOURCES/0007-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0008-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0009-Added-SM-Driver-for-MooseFS.patch
- SOURCES/0010-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch
- SOURCES/0011-MooseFS-SR-uses-now-UUID-subdirs-for-each-SR.patch
- SOURCES/0012-Fix-is_open-call-for-many-drivers-25.patch
- SOURCES/0013-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
- SOURCES/0014-Fix-code-coverage-regarding-MooseFSSR-and-ZFSSR-29.patch
- SOURCES/0015-py3-simple-changes-from-futurize-on-XCP-ng-drivers.patch
- SOURCES/0016-py3-futurize-fix-of-xmlrpc-calls-for-CephFS-GlusterF.patch
- SOURCES/0017-py3-use-of-integer-division-operator.patch
- SOURCES/0018-test_on_slave-allow-to-work-with-SR-using-absolute-P.patch
- SOURCES/0019-py3-switch-interpreter-to-python3.patch
- SOURCES/0020-Support-recent-version-of-coverage-tool.patch
- SOURCES/0021-Fix-blktap-error-mapping-in-python3.patch
- SOURCES/0022-feat-LinstorSR-import-all-8.2-changes.patch
- SOURCES/0023-feat-LinstorSR-is-now-compatible-with-python-3.patch
- SPECS/sm.spec
- Add 0021-Fix-blktap-error-mapping-in-python3.patch
- Add 0022-feat-LinstorSR-import-all-8.2-changes.patch
- Add 0023-feat-LinstorSR-is-now-compatible-with-python-3.patch
> LINSTOR driver support for XCP-ng 8.3

- SOURCES/0001-backport-of-ccd121cc248d79b749a63d4ad099e6d5f4b8b588.patch
- SOURCES/0002-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0003-Add-TrueNAS-multipath-config.patch
- SOURCES/0004-feat-drivers-add-CephFS-GlusterFS-and-XFS-drivers.patch
- SOURCES/0005-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0006-Re-add-the-ext4-driver-for-users-who-need-to-transit.patch
- SOURCES/0007-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0008-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0009-If-no-NFS-ACLs-provided-assume-everyone.patch
- SOURCES/0010-Added-SM-Driver-for-MooseFS.patch
- SOURCES/0011-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch
- SOURCES/0012-MooseFS-SR-uses-now-UUID-subdirs-for-each-SR.patch
- SOURCES/0013-Fix-is_open-call-for-many-drivers-25.patch
- SOURCES/0014-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
- SOURCES/0015-Remove-SR_PROBE-from-ZFS-capabilities-37.patch
- SOURCES/0016-Fix-vdi-ref-when-static-vdis-are-used.patch
- SOURCES/0017-Tell-users-not-to-edit-multipath.conf-directly.patch
- SOURCES/0018-Add-custom.conf-multipath-configuration-file.patch
- SOURCES/0019-Install-etc-multipath-conf.d-custom.conf.patch
- SOURCES/ca-375968-multi-session-iscsi
- SOURCES/ca-379329-check-for-missing
- SOURCES/cp-45514-set-ownership-and
- SPECS/sm.spec
Koji build v8.2-incoming, scratch: http://koji.xcp-ng.org/taskinfo?taskID=40621
> 8.2 rebase hotfixes

- SOURCES/0001-backport-of-ccd121cc248d79b749a63d4ad099e6d5f4b8b588.patch
- SOURCES/0002-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0003-Add-TrueNAS-multipath-config.patch
- SOURCES/0004-feat-drivers-add-CephFS-GlusterFS-and-XFS-drivers.patch
- SOURCES/0005-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0006-Re-add-the-ext4-driver-for-users-who-need-to-transit.patch
- SOURCES/0007-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0008-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0009-If-no-NFS-ACLs-provided-assume-everyone.patch
- SOURCES/0010-Added-SM-Driver-for-MooseFS.patch
- SOURCES/0011-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch
- SOURCES/0012-MooseFS-SR-uses-now-UUID-subdirs-for-each-SR.patch
- SOURCES/0013-Fix-is_open-call-for-many-drivers-25.patch
- SOURCES/0014-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
- SOURCES/0015-Remove-SR_PROBE-from-ZFS-capabilities-37.patch
- SOURCES/0016-Fix-vdi-ref-when-static-vdis-are-used.patch
- SOURCES/0017-Tell-users-not-to-edit-multipath.conf-directly.patch
- SOURCES/0018-Add-custom.conf-multipath-configuration-file.patch
- SOURCES/0019-Install-etc-multipath-conf.d-custom.conf.patch
- SOURCES/ca-375367-nfs-timeout
- SOURCES/ca-379315-use-xe_sr_errorcodes
- SOURCES/ca-381221-increase-nfs
- SOURCES/cp-45927-change-equalogic-checker
- SPECS/sm.spec
Koji build (scratch, 8.2-incoming): http://koji.xcp-ng.org/taskinfo?taskID=44060
> 8.2 rebase hotfixes (XS82ECU1056)

- SOURCES/0001-backport-of-ccd121cc248d79b749a63d4ad099e6d5f4b8b588.patch
- SOURCES/0002-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0003-Add-TrueNAS-multipath-config.patch
- SOURCES/0004-feat-drivers-add-CephFS-GlusterFS-and-XFS-drivers.patch
- SOURCES/0005-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0006-Re-add-the-ext4-driver-for-users-who-need-to-transit.patch
- SOURCES/0007-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0008-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0009-If-no-NFS-ACLs-provided-assume-everyone.patch
- SOURCES/0010-Added-SM-Driver-for-MooseFS.patch
- SOURCES/0011-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch
- SOURCES/0012-MooseFS-SR-uses-now-UUID-subdirs-for-each-SR.patch
- SOURCES/0013-Fix-is_open-call-for-many-drivers-25.patch
- SOURCES/0014-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
- SOURCES/0015-Remove-SR_PROBE-from-ZFS-capabilities-37.patch
- SOURCES/0016-Fix-vdi-ref-when-static-vdis-are-used.patch
- SOURCES/0017-Tell-users-not-to-edit-multipath.conf-directly.patch
- SOURCES/0018-Add-custom.conf-multipath-configuration-file.patch
- SOURCES/0019-Install-etc-multipath-conf.d-custom.conf.patch
- SOURCES/0020-Backport-NFS4-only-support.patch
- SOURCES/0021-Backport-probe-for-NFS4-when-rpcinfo-does-not-includ.patch
- SPECS/sm.spec
See: https://github.com/xcp-ng/sm/pull/49
> Backport support NFS4 only

- SOURCES/0028-feat-LargeBlock-introduce-largeblocksr-51.patch
- SPECS/sm.spec
Koji build (v8.3-incoming, scratch) : https://koji.xcp-ng.org/taskinfo?taskID=50083
> Add patch for Largeblock driver

- SOURCES/0028-feat-LargeBlock-introduce-largeblocksr-51.patch
- SPECS/sm.spec
Add a clearer error message for multi devices not working
> Update patch for LargeBlock driver

- SOURCES/0022-feat-LargeBlock-backport-of-largeblocksr-51.patch
- SPECS/sm.spec
Koji build (v8.2-incoming, scratch) : https://koji.xcp-ng.org/taskinfo?taskID=52508
> Add LargeBlockSR to 8.2

- SPECS/sm.spec
We must reload the multipathd configuration without restarting the service to prevent the opening of /dev/drbdXXXX volumes. Otherwise if multipathd opens a DRBD volume, it blocks its access to other hosts.
> 8.2: Reload automatically multipathd configuration

- SOURCES/0019-feat-LinstorSR-import-all-8.2-changes.patch
- SOURCES/0020-feat-LinstorSR-is-now-compatible-with-python-3.patch
- SOURCES/0021-Remove-SR_PROBE-from-ZFS-capabilities-36.patch
- SOURCES/0022-Repair-coverage-to-be-compatible-with-8.3-test-env.patch
- SOURCES/0023-Support-IPv6-in-Ceph-Driver.patch
- SOURCES/0024-lvutil-use-wipefs-not-dd-to-clear-existing-signature.patch
- SOURCES/0025-feat-LargeBlock-introduce-largeblocksr-51.patch
- SPECS/sm.spec
Koji build (scratch, v8.3-incoming): http://koji.xcp-ng.org/taskinfo?taskID=59535
> Fix 3.2.0 rebase which prevents VMs from starting

- SPECS/sm.spec
We must reload the multipathd configuration without restarting the service to prevent the opening of /dev/drbdXXXX volumes. Otherwise if multipathd opens a DRBD volume, it blocks its access to other hosts.
> 8.3: Reload automatically multipathd configuration

- SOURCES/0001-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0002-feat-drivers-add-CephFS-and-GlusterFS-drivers.patch
- SOURCES/0003-feat-drivers-add-XFS-driver.patch
- SOURCES/0004-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0005-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0006-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0007-Added-SM-Driver-for-MooseFS.patch
- SOURCES/0008-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch
- SOURCES/0009-MooseFS-SR-uses-now-UUID-subdirs-for-each-SR.patch
- SOURCES/0010-Fix-is_open-call-for-many-drivers-25.patch
- SOURCES/0011-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
- SOURCES/0012-Fix-code-coverage-regarding-MooseFSSR-and-ZFSSR-29.patch
- SOURCES/0013-py3-simple-changes-from-futurize-on-XCP-ng-drivers.patch
- SOURCES/0014-py3-futurize-fix-of-xmlrpc-calls-for-CephFS-GlusterF.patch
- SOURCES/0015-py3-use-of-integer-division-operator.patch
- SOURCES/0016-test_on_slave-allow-to-work-with-SR-using-absolute-P.patch
- SOURCES/0017-py3-switch-interpreter-to-python3.patch
- SOURCES/0018-Support-recent-version-of-coverage-tool.patch
- SOURCES/0019-feat-LinstorSR-import-all-8.2-changes.patch
- SOURCES/0020-feat-LinstorSR-is-now-compatible-with-python-3.patch
- SOURCES/0021-Remove-SR_PROBE-from-ZFS-capabilities-36.patch
- SOURCES/0022-Repair-coverage-to-be-compatible-with-8.3-test-env.patch
- SOURCES/0023-Support-IPv6-in-Ceph-Driver.patch
- SOURCES/0024-lvutil-use-wipefs-not-dd-to-clear-existing-signature.patch
- SOURCES/0025-feat-LargeBlock-introduce-largeblocksr-51.patch
- SOURCES/0026-feat-LVHDSR-add-a-way-to-modify-config-of-LVMs-60.patch
- SOURCES/0027-Revert-CA-379329-check-for-missing-iSCSI-sessions-an.patch
- SPECS/sm.spec
See: https://github.com/xcp-ng/sm/pull/66
> Fix disconnected iSCSI SR (error 202)

- SOURCES/0001-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0002-feat-drivers-add-CephFS-and-GlusterFS-drivers.patch
- SOURCES/0003-feat-drivers-add-XFS-driver.patch
- SOURCES/0004-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0005-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0006-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0007-Added-SM-Driver-for-MooseFS.patch
- SOURCES/0008-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch
- SOURCES/0009-MooseFS-SR-uses-now-UUID-subdirs-for-each-SR.patch
- SOURCES/0010-Fix-is_open-call-for-many-drivers-25.patch
- SOURCES/0011-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
- SOURCES/0012-Fix-code-coverage-regarding-MooseFSSR-and-ZFSSR-29.patch
- SOURCES/0013-py3-simple-changes-from-futurize-on-XCP-ng-drivers.patch
- SOURCES/0014-py3-futurize-fix-of-xmlrpc-calls-for-CephFS-GlusterF.patch
- SOURCES/0015-py3-use-of-integer-division-operator.patch
- SOURCES/0016-test_on_slave-allow-to-work-with-SR-using-absolute-P.patch
- SOURCES/0017-py3-switch-interpreter-to-python3.patch
- SOURCES/0018-Support-recent-version-of-coverage-tool.patch
- SOURCES/0019-feat-LinstorSR-import-all-8.2-changes.patch
- SOURCES/0020-feat-LinstorSR-is-now-compatible-with-python-3.patch
- SOURCES/0021-Remove-SR_PROBE-from-ZFS-capabilities-36.patch
- SOURCES/0022-Repair-coverage-to-be-compatible-with-8.3-test-env.patch
- SOURCES/0023-Support-IPv6-in-Ceph-Driver.patch
- SOURCES/0024-lvutil-use-wipefs-not-dd-to-clear-existing-signature.patch
- SOURCES/0025-feat-LargeBlock-introduce-largeblocksr-51.patch
- SOURCES/0026-feat-LVHDSR-add-a-way-to-modify-config-of-LVMs-60.patch
- SOURCES/0027-Revert-CA-379329-check-for-missing-iSCSI-sessions-an.patch
- SOURCES/sm-3.2.0.tar.gz
- SOURCES/sm-3.2.1.tar.gz
- SPECS/sm.spec
[v8.3-incoming scratch build](https://koji.xcp-ng.org/taskinfo?taskID=62880)
> Update to 3.2.1

- SPECS/sm.spec
Fixes update warning.
Related to https://github.com/xapi-project/sm/issues/705
> Don't try to patch /etc/cgrules.conf when the patch was already applied

- SOURCES/0001-backport-of-ccd121cc248d79b749a63d4ad099e6d5f4b8b588.patch
- SOURCES/0002-Update-xs-sm.service-s-description-for-XCP-ng.patch
- SOURCES/0003-Add-TrueNAS-multipath-config.patch
- SOURCES/0004-feat-drivers-add-CephFS-GlusterFS-and-XFS-drivers.patch
- SOURCES/0005-feat-drivers-add-ZFS-driver-to-avoid-losing-VDI-meta.patch
- SOURCES/0006-Re-add-the-ext4-driver-for-users-who-need-to-transit.patch
- SOURCES/0007-feat-drivers-add-LinstorSR-driver.patch
- SOURCES/0008-feat-tests-add-unit-tests-concerning-ZFS-close-xcp-n.patch
- SOURCES/0009-If-no-NFS-ACLs-provided-assume-everyone.patch
- SOURCES/0010-Added-SM-Driver-for-MooseFS.patch
- SOURCES/0011-Avoid-usage-of-umount-in-ISOSR-when-legacy_mode-is-u.patch
- SOURCES/0012-MooseFS-SR-uses-now-UUID-subdirs-for-each-SR.patch
- SOURCES/0013-Fix-is_open-call-for-many-drivers-25.patch
- SOURCES/0014-Remove-SR_CACHING-capability-for-many-SR-types-24.patch
- SOURCES/0015-Remove-SR_PROBE-from-ZFS-capabilities-37.patch
- SOURCES/0016-Fix-vdi-ref-when-static-vdis-are-used.patch
- SOURCES/0017-Tell-users-not-to-edit-multipath.conf-directly.patch
- SOURCES/0018-Add-custom.conf-multipath-configuration-file.patch
- SOURCES/0019-Install-etc-multipath-conf.d-custom.conf.patch
- SOURCES/0020-Backport-NFS4-only-support.patch
- SOURCES/0021-Backport-probe-for-NFS4-when-rpcinfo-does-not-includ.patch
- SOURCES/0022-feat-LargeBlock-backport-of-largeblocksr-51-55.patch
- SOURCES/0023-feat-LVHDSR-add-a-way-to-modify-config-of-LVMs-56.patch
- SOURCES/CA-393194-Fix-pvremove-failure
- SOURCES/CP-49961-update-multipath
- SOURCES/CP-50251-update-multipath
- SOURCES/clean-up-regex-on-hp-hpe
- SOURCES/feat-add-HPE-Nimble-multipath
- SOURCES/update-multipath.conf-with
- SPECS/sm.spec
Koji build (scratch, v8.2-incoming): http://koji.xcp-ng.org/taskinfo?taskID=67159
> Import XS82ECU1075 (8.2)

- SOURCES/0059-Use-override-everywhere.patch
- SOURCES/0060-Makefile-fix-don-t-execute-precheck-during-installat.patch
- SPECS/sm.spec
Koji build (scratch, v8.3-incoming): http://koji.xcp-ng.org/taskinfo?taskID=72390
> Fix missing mypy "@override" import in nfs-on-slave script

- SOURCES/ca-405381_mpathcount_info_does_not_automatically_refresh_in_xencenter_after_disabling_and_enabling_multipath.patch
- SPECS/sm.spec
> Packaging fixes for v9
